import type { SupabaseClient } from '@supabase/supabase-js';

/** Strip the bracketed service tag (e.g. "[DEV] ", "[PROPOSAL] ") from an order topic. */
export function cleanTopic(topic: string): string {
  return (topic || '').replace(/^\[[^\]]+\]\s*/g, '').trim();
}

interface OrderLike {
  order_id: string;
  legal_name?: string | null;
  guest_name?: string | null;
  email?: string | null;
  guest_email?: string | null;
  client_phone?: string | null;
  whatsapp_sync?: string | null;
  guest_whatsapp?: string | null;
  client_company?: string | null;
  client_address?: string | null;
  topic: string;
  additional_info?: string | null;
  financial_quote?: number | null;
  payment_milestones?: any[] | null;
  sixty_percent_paid?: boolean | null;
  forty_percent_paid?: boolean | null;
  payment_structure_type?: string | null;
}

export interface InvoiceDefaults {
  contact_email: string;
  bank_name: string;
  account_name: string;
  account_number: string;
  developer_signature_name: string;
  default_terms: string[];
  default_deliverables: any[];
  default_additional_services: string[];
  default_exclusions: string[];
  default_timeline: any[];
}

const FALLBACK_DEFAULTS: InvoiceDefaults = {
  contact_email: 'yourwriterofficial@gmail.com',
  bank_name: 'Opay',
  account_name: 'Richlord Jude',
  account_number: '8121443666',
  developer_signature_name: 'Richlord Jude',
  default_terms: [
    'Payments made in Nigerian Naira (₦).',
    'Invoices due immediately upon receipt.',
    'Full IP rights transfer upon final payment.',
    '365 days of support and bug fixes post delivery.',
  ],
  default_deliverables: [],
  default_additional_services: [],
  default_exclusions: [],
  default_timeline: [],
};

export async function getInvoiceDefaults(supabase: SupabaseClient): Promise<InvoiceDefaults> {
  try {
    const { data } = await supabase.from('invoice_defaults').select('*').eq('id', 1).single();
    if (data) return { ...FALLBACK_DEFAULTS, ...data };
  } catch { /* fall through */ }
  return FALLBACK_DEFAULTS;
}

/** Build the milestones array for an invoice from an order's payment structure. */
function milestonesFromOrder(order: OrderLike): any[] {
  const total = Number(order.financial_quote || 0);
  const existing = order.payment_milestones;
  if (Array.isArray(existing) && existing.length > 0) {
    return existing.map((m: any) => ({
      name: m.name,
      percentage: m.percentage,
      amount: m.amount ?? Math.round((Number(m.percentage) / 100) * total),
      paid: !!m.paid,
      delivered: !!m.delivered,
      paid_at: m.paid_at ?? null,
      tx_ref: m.tx_ref ?? null,
      trigger: m.trigger ?? '',
    }));
  }
  // Standard 60/40 fallback
  return [
    { name: 'Initial Deposit', percentage: 60, amount: Math.round(total * 0.6), paid: !!order.sixty_percent_paid, delivered: false, paid_at: null, tx_ref: null, trigger: 'Upon signing this agreement' },
    { name: 'Final Payment', percentage: 40, amount: Math.round(total * 0.4), paid: !!order.forty_percent_paid, delivered: false, paid_at: null, tx_ref: null, trigger: 'Upon project completion' },
  ];
}

function statusFromMilestones(milestones: any[]): 'PENDING' | 'PARTIALLY_PAID' | 'PAID' {
  const paidCount = milestones.filter(m => m.paid).length;
  if (paidCount === 0) return 'PENDING';
  if (paidCount === milestones.length) return 'PAID';
  return 'PARTIALLY_PAID';
}

/**
 * Creates (or updates) a custom_invoices row mirroring an order. Uses
 * invoice_number = order_id so the public invoice page and the Paystack
 * milestone flow both resolve to the same underlying order.
 * Idempotent: safe to call more than once for the same order.
 */
export async function upsertInvoiceForOrder(
  supabase: SupabaseClient,
  order: OrderLike,
  opts: { autoGenerated?: boolean } = {}
): Promise<{ invoiceNumber: string; invoiceId: number | null; totalAmount: number } | null> {
  const defaults = await getInvoiceDefaults(supabase);
  const milestones = milestonesFromOrder(order);
  const total = Number(order.financial_quote || 0);

  const payload: any = {
    invoice_number: order.order_id,
    order_id: order.order_id,
    client_name: order.legal_name || order.guest_name || 'Client',
    company_name: order.client_company || null,
    address: order.client_address || null,
    email: order.email || order.guest_email || '',
    phone: order.client_phone || order.whatsapp_sync || order.guest_whatsapp || null,
    project_title: cleanTopic(order.topic) || 'Project',
    project_description: order.additional_info || null,
    deliverables: defaults.default_deliverables,
    additional_services: defaults.default_additional_services,
    exclusions: defaults.default_exclusions,
    timeline: defaults.default_timeline,
    milestones,
    payment_details: {
      bank_name: defaults.bank_name,
      account_name: defaults.account_name,
      account_number: defaults.account_number,
    },
    terms: defaults.default_terms,
    developer_signature_name: defaults.developer_signature_name,
    client_signature_name: order.legal_name || order.guest_name || 'Client',
    status: statusFromMilestones(milestones),
    total_amount: total,
    currency: '₦',
    auto_generated: opts.autoGenerated ?? false,
    updated_at: new Date().toISOString(),
  };

  const { data, error } = await supabase
    .from('custom_invoices')
    .upsert(payload, { onConflict: 'invoice_number' })
    .select('id')
    .single();

  if (error) {
    console.warn('[invoices] upsertInvoiceForOrder failed:', error.message);
    return null;
  }

  return { invoiceNumber: order.order_id, invoiceId: data?.id ?? null, totalAmount: total };
}
